/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.n52.project.enforce.cs8.api;

import org.n52.project.enforce.cs8.model.Error;
import org.n52.project.enforce.cs8.model.FeatureCollection;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-16T11:07:35.055622800+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "cs8", description = "the cs8 API")
public interface Cs8Api {

    /**
     * POST /cs8_pfos_data : Add CS 58 data
     * Add CS 8 data
     *
     * @param body feature data (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addCs8DataAsBody",
        summary = "Add CS 58 data",
        description = "Add CS 8 data",
        tags = { "cs8" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/cs8_pfos_data",
        produces = { "application/json" },
        consumes = { "application/enforce-cs8-data" }
    )
    
    ResponseEntity<?> addCs8DataAsBody(
        @Parameter(name = "body", description = "feature data", required = true) @Valid @RequestBody org.springframework.core.io.Resource body
    );


    /**
     * GET /cs8_pfos_data : get data gathered by CS 8
     * get data gathered by CS 8
     *
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getCs8Data",
        summary = "get data gathered by CS 8",
        description = "get data gathered by CS 8",
        tags = { "cs8" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = FeatureCollection.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = FeatureCollection.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/cs8_pfos_data",
        produces = { "application/vnd.geo+json", "application/json" }
    )
    
    ResponseEntity<?> getCs8Data(
        
    );

}
